dist: bionic
language: go
go:
  - 1.14.13
before_script:
  - echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04 /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
  - curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04/Release.key | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get -qq -y install podman
script:
  - make check
  - make BUNDLE_DIR=/tmp MOCK_BUNDLE=true release
