build: off
clone_folder: c:\gopath\src\github.com\code-ready\crc
environment:
  GOPATH: c:\gopath
image: Visual Studio 2019
before_test:
  - choco install make
  - choco install wixtoolset
  - set PATH=C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin;%PATH%
  - set PATH=C:\go116;%WIX%bin;%PATH%
  - make out/windows-amd64/crc-windows-installer.zip
  - make cross
test_script:
  - make test
artifacts:
  - path: out\linux-amd64\crc
    name: crc linux executable
    type: File
  - path: out\macos-amd64\crc
    name: crc darwin
    type: File
  - path: out\windows-amd64\crc.exe
    name: crc windows executable
    type: File
  - path: out\windows-amd64\crc-windows-installer.zip
    name: crc windows installer
    type: Zip
