## Circleci version
version: 2

## Machine specific variable
jobs:
  build:
    macos:
      xcode: "10.0.0"
    environment:
      GOVERSION: "1.15.13"

## Build crc
    steps:
    - checkout
    - run:
        name: Configure GOPATH
        command: echo 'export GOPATH=$HOME/go' >> $BASH_ENV
    - run:
        name: Configure Path
        command: echo 'export PATH=$GOPATH/bin:/usr/local/go/bin/:$PATH' >> $BASH_ENV
    - run:
        name: Cleanup GOROOT
        command: sudo rm -rf /usr/local/go
    - run:
        name: Install go
        command: curl --http1.1 https://dl.google.com/go/go${GOVERSION}.darwin-amd64.tar.gz | sudo tar -C /usr/local -xz
    - run:
        name: List go version
        command: go version
    - run:
        name: List go environment
        command: go env
    - run:
        name: Make
        command: make check
    - run:
        name: mock make out/macos-amd64/crc-macos-amd64.pkg
        command: make NO_CODESIGN=1 BUNDLE_DIR=/tmp MOCK_BUNDLE=true out/macos-amd64/crc-macos-amd64.pkg
    - store_artifacts:
        path: ~/project/out
        destination: crc

  build_mock_release:
    machine:
      image: ubuntu-2004:202101-01
    environment:
      GOVERSION: "1.15.13"
      CONTAINER_RUNTIME: "docker"
    steps:
      - checkout
      - run:
          name: Configure GOPATH
          command: echo 'export GOPATH=$HOME/go' >> $BASH_ENV
      - run:
          name: Configure Path
          command: echo 'export PATH=$GOPATH/bin:/usr/local/go/bin/:$PATH' >> $BASH_ENV
      - run:
          name: Cleanup GOROOT
          command: sudo rm -rf /usr/local/go
      - run:
          name: Install go
          command: curl https://dl.google.com/go/go${GOVERSION}.linux-amd64.tar.gz | sudo tar -C /usr/local -xz
      - run:
          name: List go version
          command: go version
      - run:
          name: List go environment
          command: go env
      - run:
          name: mock make release
          command: make BUNDLE_DIR=/tmp MOCK_BUNDLE=true release
      - run:
          name: make rpm
          command: CONTAINER_RUNTIME=docker make test-rpmbuild

  build_docs:
    machine:
      image: ubuntu-2004:202101-01
    environment:
      CONTAINER_RUNTIME: "docker"
    steps:
    - checkout
    - run:
        name: Make build_docs
        # force GOPATH to a sane value as the image we are using has an older go version
        # with a 'go env GOPATH' output which causes make failures
        command: make GOPATH="/home/circleci/go" build_docs
    - run:
        name: Check links in docs
        command: make GOPATH="/home/circleci/go" docs_check_links
    - persist_to_workspace:
        root: docs/build
        paths: index.html

  docs_deploy:
    machine:
      image: ubuntu-2004:202101-01
    steps:
    - attach_workspace:
        at: docs/build
    - add_ssh_keys:
        fingerprints:
          - "c5:64:d4:79:8f:c7:9b:80:b8:16:71:20:57:6b:8c:94"
    - run:
        name: Configure git
        command: |
          cd docs/build/
          git init
          git remote add origin git@github.com:code-ready/crc.git
          git config user.email "codereadycontainers@gmail.com"
          git config user.name "crc-bot"
    - run:
        name: Deploy docs to gh-pages branch
        command: |
          cd docs/build/
          git checkout -b gh-pages
          git add .
          git commit -m "[skip ci] Docs update"
          git push origin HEAD -f

workflows:
  version: 2
  build:
    jobs:
      - build
      - build_mock_release
      - build_docs
      - docs_deploy:
          requires:
            - build
            - build_docs
          filters:
            branches:
              only: master
