name: Test MicroShift preset
on:
  push:
    branches:
      - "main"
  pull_request: {}
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macOS-latest
          - macOS-11
        go:
          - 1.19
    steps:
      # Enable tmate debugging of manually-triggered workflows if the input option was provided
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
        with:
          limit-access-to-actor: true
        timeout-minutes: 30
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: check if OCP_PULL_SECRET exists
        shell: bash
        run: |
          if [ ${PULL_SECRET} == "" ]; then
            echo "The secret \"OCP_PULL_SECRET\" is not set; echo please go to \"settings > secrets > actions\" to create it"
            exit 1
          fi
        env:
          PULL_SECRET: ${{ secrets.OCP_PULL_SECRET }}
      - name: Write the pull secret to json file
        shell: bash
        run: |
          echo $PULL_SECRET > temp-ps.json
        env:
          PULL_SECRET: ${{ secrets.OCP_PULL_SECRET }}
      - name: Build macOS installer
        run: make NO_CODESIGN=1 out/macos-universal/crc-macos-installer.pkg
      - name: Install crc pkg
        run: sudo installer -pkg out/macos-universal/crc-macos-installer.pkg -target /
      - name: Set microshift preset as part of config
        run: crc config set preset microshift
      - name: Run crc setup command
        run: crc setup
      - name: Wait 10 sec for the daemon to serve
        run: sleep 10
      - name: Run crc with microshift preset
        run: crc start --pull-secret-file temp-ps.json
